apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: todoapi
build:
  googleCloudBuild: {}
  artifacts:
    - image: asia-east1-docker.pkg.dev/shawnho-looker-2024/shawnho-looker-2024/webapi-crud
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s-manifests/deployment.yaml
    - k8s-manifests/service.yaml
    - k8s-manifests/todo-istio.yaml
