apiVersion: v1
kind: Secret
metadata:
  name: db-pw-db0
type: Opaque
data:
  db0: "YWRtaW4="
---
apiVersion: alloydbomni.dbadmin.goog/v1
kind: DBCluster
metadata:
  name: db0
spec:
  databaseVersion: "15.5.0"
  primarySpec:
    adminUser:
      passwordRef:
        name: db-pw-db0
    resources:
      cpu: 2
      memory: 8Gi
      disks:
      - name: DataDisk
        size: 10Gi
        storageClass: standard
