apiVersion: v1
data:
  mesh: |
    enableTracing: true
      extensionProviders:
      - name: otel-tracing
        opentelemetry:
          port: 4317
          service: bindplane-node-agent.bindplane-agent.svc.cluster.local
          resource_detectors:
            environment: {}

    # This section can be updated with user configuration settings from https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
    # Some options required for ASM to not be modified will be ignored
kind: ConfigMap
metadata:
  name: istio-asm-managed-rapid
  namespace: istio-system
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-demo
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
    customTags:
      "service":
        literal:
          value: "todoapi"
